PDF_OCR/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('PDF_TESS.urls'))
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PDF_TESS/urls.py
from django.urls import path
from . import views
from django.conf import settings

urlpatterns = [
    path('upload_pdf/', views.upload_pdf, name='upload_pdf'),
    path('pdf_list/', views.pdf_list, name='pdf_list'),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PDF_TESS/models.py
from django.db import models

class PDF(models.Model):
    file = models.FileField(upload_to='pdfs/')

class ExtractedText(models.Model):
    pdf = models.ForeignKey(PDF, on_delete=models.CASCADE)
    page_number = models.IntegerField()
    text = models.TextField()
    image_path = models.ImageField(upload_to='images/', null=True, blank=True)

PDF_TESS/forms.py
from django import forms

class PDFUploadForm(forms.Form):
    pdf_file = forms.FileField(label='Upload a PDF')

PDF_TESS/views.py
from django.shortcuts import render, redirect
from .models import PDF, ExtractedText
import pytesseract
from .forms import PDFUploadForm
from pdf2image import convert_from_path
import os
from django.conf import settings
import cv2
import numpy as np
from django.conf import settings
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage

def upload_pdf(request):
    if request.method == 'POST':
        form = PDFUploadForm(request.POST, request.FILES)
        if form.is_valid():
            pdf_file = request.FILES['pdf_file']
            pdf = PDF(file=pdf_file)
            pdf.save()

            images = convert_from_path(pdf.file.path)
            pytesseract.pytesseract.tesseract_cmd = (r"C:\Program Files\Tesseract-OCR\tesseract.exe")
            
            for i, image in enumerate(images):
                image_filename = f'{pdf.file.name}_page_{i+1}.png'
                image_path = os.path.join(settings.MEDIA_ROOT, 'images', image_filename.replace('/', '_'))


                # Save the image
                image.save(image_path)

                result = preprocess_image(image_path)
                
                prepro_path = os.path.join(settings.MEDIA_ROOT, 'prepro', image_filename.replace('/', '_'))
                
                cv2.imwrite(prepro_path + f'{pdf.file.name}_page_{i+1}.png', result)

                # Save the image path in the database
                text = pytesseract.image_to_string(image, lang='mar')
                extracted_text = ExtractedText(pdf=pdf, page_number=i+1, text=text, image_path=image_path)
                extracted_text.save()

            return redirect('pdf_list')

    else:
        form = PDFUploadForm()
    return render(request, 'upload_pdf.html', {'form': form})

def pdf_list(request):
    pdfs = PDF.objects.all()
    return render(request, 'pdf_list.html', {'pdfs': pdfs})


def preprocess_image(image_path):
    # Read the original image
    original_img = cv2.imread(image_path, cv2.IMREAD_COLOR)

    # Convert to grayscale
    gray = cv2.cvtColor(original_img, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (5, 5), 0)

    # Apply thresholding
    _, binary = cv2.threshold(blur, 160, 220, cv2.THRESH_BINARY)

    #remove borders
    
    # Noise reduction
    # denoised = noise_removal(binary)

    #Deskew Image
    def deskew(cvImage):
        angle = getSkewAngle(cvImage)
        return rotateImage(cvImage, -1.0 * angle)
    fixed = deskew(binary)
    no_borders = remove_borders(fixed)
    
    return no_borders

def noise_removal(image):
    kernel = np.ones((1, 1), np.uint8)
    image = cv2.dilate(image, kernel, iterations=1)
    image = cv2.GaussianBlur(image, (5,5),0)
    return (image)

def getSkewAngle(cvImage):
    # Prep image, copy, convert to gray scale, blur, and threshold
    newImage = cvImage.copy()

    # Find all contours
    contours, hierarchy = cv2.findContours(newImage, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
    contours = sorted(contours, key = cv2.contourArea, reverse = True)
    for c in contours:
        rect = cv2.boundingRect(c)
        x,y,w,h = rect
        cv2.rectangle(newImage,(x,y),(x+w,y+h),(0,255,0),2)

    # Find largest contour and surround in min area box
    largestContour = contours[0]
    print (len(contours))
    minAreaRect = cv2.minAreaRect(largestContour)
    cv2.imwrite("temp/boxes.jpg", newImage)
    # Determine the angle. Convert it to the value that was originally used to obtain skewed image
    angle = minAreaRect[-1]
    print(angle)
    if angle < -45:
        angle = 90 + angle
    return -1.0 * angle
# Rotate the image around its center
def rotateImage(cvImage, angle: float):
    newImage = cvImage.copy()
    (h, w) = newImage.shape[:2]
    center = (w // 2, h // 2)
    M = cv2.getRotationMatrix2D(center, angle, 1.0)
    newImage = cv2.warpAffine(newImage, M, (w, h), flags=cv2.INTER_CUBIC, borderMode=cv2.BORDER_REPLICATE)
    return newImage
# Deskew image

def remove_borders(image):
    contours, heiarchy = cv2.findContours(image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    cntsSorted = sorted(contours, key=lambda x:cv2.contourArea(x))
    cnt = cntsSorted[-1]
    x, y, w, h = cv2.boundingRect(cnt)
    crop = image[y:y+h, x:x+w]
    return (crop)
#++++++++++++++++++++++++++++++++++++++++++++++++++

PDF_TESS/templates/pdf_list.html
<!DOCTYPE html>
<html>
<head>
    <title>PDF List</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <style>
        body{
            font-family: 'Montserrat', sans-serif;
        }
        .pdf-list {
            display: flex;
        }

        .pdf-list-column {
            padding: 10px;
        }

        .pdf-list-column:first-child {
            flex: 20%;
        }

        .pdf-list-column:last-child {
            flex: 80%;
        }

        .pdf-page {
            font-weight: bold;
        }

        .pdf-name {
            font-weight: bold;
        }

        .pdf-text {
            white-space: pre-wrap;
        }
    </style>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;1,100;1,200;1,400&display=swap" rel="stylesheet">
</head>

<body>
    <div class="container">
        <h1 class="my-4">List of Uploaded PDFs</h1>
        <a class="btn btn-primary my-4" href="{% url 'upload_pdf' %}">Upload another PDF</a>
        <div class="row">
            <div class="col-md-12">
                <ul class="list-group">
                    {% for pdf in pdfs reversed %}
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-md-6"> 
                                <h3 class="d-block pdf-name">
                                    <a href="{{ pdf.file.url }}" target="_blank">{{ pdf.file.name }}</a>
                                </h3>
                            </div>
                            <div class="col-md-6"> </div>
                        </div>
                    </li>

                    {% for extracted_text in pdf.extractedtext_set.all %}
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-md-6"> 
                                <p class="d-block pdf-page">Page: {{ extracted_text.page_number }}</p>
                                <a href="{{ pdf.file.url }}#page={{ extracted_text.page_number }}" target="_blank">View Page</a>
                                <!-- <embed src="{{ pdf.file.url }}#page={{ extracted_text.page_number }}" type=""
                                width="200"
                                height="400"> -->
                            </div>
                            <div class="col-md-6"> 
                                <strong class="d-block mt-3">Extracted Text:</strong>
                                <pre class="pdf-text">{{ extracted_text.text }}</pre>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                    {% endfor %}
                </ul>
            </div>
        </div>
        
    </div>
</body>
</html>

PDF_TESS/templates/upload_pdf.html
<!DOCTYPE html>
<html>
<head>
    <title>Upload PDF</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script></head>
    <style>
        body{
            font-family: 'Montserrat', sans-serif;

        }
        .file-preview {
            display: none;
            margin-top: 20px;
        }
        .image-preview {
            max-width: 100%;
            height: 400px;
        }
    </style>
       <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
       <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;1,100;1,200;1,400&display=swap" rel="stylesheet">
   
<body style="background-color: #f1f1f1; padding: 20px;">


    <div class="container mt-5">
        <h1 class="text-center">Upload a PDF</h1>

        <form method="post" enctype="multipart/form-data" class="mt-4">
            {% csrf_token %}
            <div class="form-group">
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary">Upload PDF</button>
        </form>

        <div class="file-preview">
            <h3>File Preview</h3>
            <iframe id="pdf-preview" class="pdf-preview"></iframe>
        </div>

        <p class="mt-3 text-center">
            <a href="{% url 'pdf_list' %}" class="btn btn-secondary">View PDF List</a>
        </p>
    </div>
    

    <script>
      const fileInput = document.querySelector('input[type="file"]');
        const pdfPreview = document.getElementById('pdf-preview');
        const filePreviewContainer = document.querySelector('.file-preview');

        fileInput.addEventListener('change', function () {
            if (fileInput.files.length > 0) {
                const file = fileInput.files[0];
                if (file.type === 'application/pdf') {
                    const url = URL.createObjectURL(file);
                    pdfPreview.src = url;
                    filePreviewContainer.style.display = 'block';
                } else {
                    pdfPreview.src = '';
                    filePreviewContainer.style.display = 'none';
                }
            } else {
                pdfPreview.src = '';
                filePreviewContainer.style.display = 'none';
            }
        });
    </script>
</body>
</html>